# Generated by Django 4.2.2 on 2023-06-26 20:06

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Vaxtı')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi Adı')),
            ],
            options={
                'verbose_name': 'Siayhı',
                'verbose_name_plural': 'Siyahılar',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aşıqlama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Vaxtı')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_todos', to='todo.list', verbose_name='Siyahı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi Adı')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todolar',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.ManyToManyField(related_name='favorites', to='todo.todo', verbose_name='Favorilər')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favorilər',
            },
        ),
    ]
